### ISSUE TITLE
Events tracking

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#242]
I have tried to write down a bunch of events that I want to turn into funnels so we can see how users are getting to where they want to go. 
If you catch any double ups or events that we can get the data from something else then we can drop it. E.g. maybe we can get the deposit and withdraw data from another TX event or something.
This is just the stuff I would like to be able to track somehow.

- [x] Tap BUY (Trade Acc Item Action menu)
- [x] Tap Sell ( Trade Acc Item Action Menu)
- [x] Deposit Token To trade Acc
- [x] Withdraw Tokens from Trade Acc
- [x] Withdraw from trade item action menu
- [x] Submitted Order
- [x] Edit Price +1%
- [x] Edit Price -1%
- [x] Manual price entry
- [x] Used median price
- [x] Buy with Neo
- [x] Buy with GAS
- [x] Buy With SWTH
	(These can probably be found through looking at the trade pairs maybe?)
- [x]  Receive error for not enough funds in trade account
- [x]  Taps marketplace token card to open token details
- [x] Taps O3 wallet item to open token details
- [x] Taps portfolio item to open token details
- [x] Taps token Details BUY
- [x] Taps Token Details SELL
- [x] View open orders related to selected token.
- [x] Contract Signed through native trade
- [x] Contract signed through switcheo dapp
- [x] View orders tab
- [x] Cancel Order
- [x] View all Orders
